name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
change-template: '- $TITLE by @$AUTHOR in #$NUMBER'
category-template: '## $TITLE'

sort-by: 'title'
sort-direction: 'ascending'

include-pre-releases: true

categories:
  - title: 'Added'
    labels:
      - 'added'
  - title: 'Changed'
  - title: 'Machine translations'
    collapse-after: 20
    labels:
      - 'machine'
  - title: 'Removed'
    labels:
      - 'removed'
  - title: 'Fixed'
    labels:
      - 'fix'
      - 'bug'
  - title: 'Dependencies'
    collapse-after: 10
    labels:
      - 'dependencies'
  - title: 'Security'
    labels:
      - 'security'
      - 'security fix'
      - 'security vulnerability'

exclude-labels:
  - 'skip-changelog'

version-resolver:
  major:
    labels:
      - 'major'
      - 'removed'
  minor:
    labels:
      - 'minor'
      - 'added'
  default: patch

template: $CHANGES